baseURL = "http://rayramy04.github.io/connect-with-me/"
languageCode = "en"
defaultContentLanguage = "en"

theme = "lynx"
googleAnalytics = "G-Y0RBR99HSF"

title = "Connect with Me"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Ray"
  headline = "University student from Japan studying Computer Science and Data Science in Malaysia"
  image = "NGC133.jpg"

  links = [
    { link = { href = "https://ray-globallife.com/", text = "My Website"} },
    { twitter = "https://x.com/rayramy04" },
    { youtube = "https://www.youtube.com/channel/UC6ljdPxxc12O3BMZzHnJWHg/" },
    { note-sticky-regular = { href = "https://note.com/ll_0013py/", text = "note" } },
    { github = "https://github.com/rayramy04" },
  ]


[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
